#!/bin/bash
echo "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd\">"
echo "<url>"
echo "<loc>https://98036119lmak.ftp.sh/index.html</loc>"
echo "<lastmod>$(date +%F)</lastmod>"
echo "<priority>1.00</priority>"
echo "</url>"
echo "<url>"
echo "<loc>https://98036119lmak.ftp.sh/iframe_img.html</loc>"
echo "<lastmod>$(date +%F)</lastmod>"
echo "<priority>0.80</priority>"
echo "</url>"
echo "</urlset>"
